/**
 * @file EcoTransit.tsx
 * @description Transit optimization component coordinating shuttle schedules and public transit outbound flow metrics.
 */

"use client";

import React, { useMemo } from "react";
import { Train, Shield, Award, Clock } from "lucide-react";

interface TransitSchedule {
  line: string;
  destination: string;
  status: "on-time" | "delayed" | "boarding";
  departureTime: string;
  capacityUtilization: number; // 0.0 - 1.0
  co2SavedKg: number;
}

const SCHEDULES: TransitSchedule[] = [
  {
    line: "Express Shuttle 1",
    destination: "Secaucus Junction (Train Connection)",
    status: "boarding",
    departureTime: "10:15 PM",
    capacityUtilization: 0.85,
    co2SavedKg: 120,
  },
  {
    line: "Express Shuttle 2",
    destination: "Secaucus Junction (Train Connection)",
    status: "on-time",
    departureTime: "10:25 PM",
    capacityUtilization: 0.40,
    co2SavedKg: 95,
  },
  {
    line: "Rapid Transit Subway",
    destination: "NYC Penn Station",
    status: "on-time",
    departureTime: "10:30 PM",
    capacityUtilization: 0.95,
    co2SavedKg: 340,
  },
  {
    line: "Park & Ride Loop",
    destination: "Lot K Parking",
    status: "delayed",
    departureTime: "10:40 PM",
    capacityUtilization: 0.20,
    co2SavedKg: 45,
  },
];

export const EcoTransit: React.FC = React.memo(() => {
  const stats = useMemo(() => {
    const totalSaved = SCHEDULES.reduce((acc, curr) => acc + curr.co2SavedKg, 0);
    const avgUtilization = SCHEDULES.reduce((acc, curr) => acc + curr.capacityUtilization, 0) / SCHEDULES.length;
    return { totalSaved, avgUtilization };
  }, []);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6" role="region" aria-label="EcoTransit: Sustainability Matrix & Transit Gantt">
      {/* Sustainability Metrics Card */}
      <div className="lg:col-span-1 flex flex-col gap-6 bg-zinc-900/50 backdrop-blur border border-zinc-800 p-6 rounded-2xl shadow-xl">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Award className="text-emerald-500 w-5 h-5" aria-hidden="true" />
            Ecological Impact Matrix
          </h2>
          <p className="text-zinc-400 text-sm mt-1">
            Real-time tracking of carbon offsets generated by public transit usage.
          </p>
        </div>

        <div className="flex flex-col gap-4">
          {/* Carbon Offset Stats */}
          <div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800 flex items-center gap-4">
            <div className="bg-emerald-500/10 p-3 rounded-lg border border-emerald-500/20 text-emerald-400">
              <Shield className="w-6 h-6" />
            </div>
            <div>
              <span className="text-[10px] text-zinc-500 font-bold uppercase tracking-wider">Total CO₂ Saved</span>
              <span className="block text-2xl font-black text-white">{stats.totalSaved} kg</span>
            </div>
          </div>

          {/* Average Utilization */}
          <div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800 flex items-center gap-4">
            <div className="bg-blue-500/10 p-3 rounded-lg border border-blue-500/20 text-blue-400">
              <Train className="w-6 h-6" />
            </div>
            <div>
              <span className="text-[10px] text-zinc-500 font-bold uppercase tracking-wider">Avg Capacity Load</span>
              <span className="block text-2xl font-black text-white">{(stats.avgUtilization * 100).toFixed(0)}%</span>
            </div>
          </div>
        </div>
      </div>

      {/* Transit Schedule Timeline (Gantt representation) */}
      <div className="lg:col-span-2 flex flex-col gap-6 bg-zinc-900/50 backdrop-blur border border-zinc-800 p-6 rounded-2xl shadow-xl">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Clock className="text-blue-500 w-5 h-5" aria-hidden="true" />
            Sustainable Transit Schedule
          </h2>
          <p className="text-zinc-400 text-sm mt-1">
            Gantt schedule tracking departures and capacity loading to optimize transit frequencies.
          </p>
        </div>

        {/* Schedule grid */}
        <div className="flex flex-col gap-4">
          {SCHEDULES.map((schedule, idx) => {
            const statusColor =
              schedule.status === "boarding" ? "text-emerald-400 bg-emerald-500/10 border-emerald-500/20" :
              schedule.status === "on-time" ? "text-blue-400 bg-blue-500/10 border-blue-500/20" :
              "text-rose-400 bg-rose-500/10 border-rose-500/20";

            return (
              <div
                key={idx}
                className="bg-zinc-950/60 border border-zinc-800/80 p-4 rounded-xl flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4"
              >
                <div className="flex flex-col gap-1">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-sm text-white">{schedule.line}</span>
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded border uppercase tracking-wider ${statusColor}`}>
                      {schedule.status}
                    </span>
                  </div>
                  <span className="text-xs text-zinc-400">{schedule.destination}</span>
                </div>

                {/* Capacity Visualizer Gantt Bar */}
                <div className="w-full sm:w-48 flex flex-col gap-1">
                  <div className="flex justify-between items-center text-[10px] text-zinc-500">
                    <span>Capacity Load</span>
                    <span className="font-bold text-zinc-300">{(schedule.capacityUtilization * 100).toFixed(0)}%</span>
                  </div>
                  <div className="w-full bg-zinc-900 rounded-full h-2 overflow-hidden border border-zinc-800">
                    <div
                      className="bg-emerald-500 h-full rounded-full transition-all duration-500"
                      style={{ width: `${schedule.capacityUtilization * 100}%` }}
                    />
                  </div>
                  <span className="text-[9px] text-zinc-500 font-mono mt-0.5">
                    Departs: <b className="text-zinc-300">{schedule.departureTime}</b> | Offset: <b className="text-emerald-400">+{schedule.co2SavedKg}kg CO₂</b>
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
});

EcoTransit.displayName = "EcoTransit";
